### ISSUE TITLE
attachToSelf() gives "stripos(): Argument #1 ($haystack) must be of type string, array given"

### ISSUE THREAD

**Issue by mikebridge** [codrasil/closurable#2]
I have this table:

```php
Schema::create('test_nodes', function (Blueprint $table) {
    $table->increments('id');
    $table->string('name');
    $table->integer('organization_id')->index();
     // ...
 });
```

and this closure table:

```php
Schema::create('test_nodes_closure', function (Blueprint $table) {
    $table->integer('ancestor_id')
        ->unsigned()
        ->index();
    $table->integer('descendant_id')
        ->unsigned()
        ->index();
    $table->integer('depth')->index()->default(0);
    $table->integer('root')->index()->default(0);
    $table->unique(['ancestor_id', 'descendant_id']);
    $table->index(['ancestor_id', 'descendant_id', 'depth']);
    $table->index(['descendant_id', 'depth']);
    $table->index(['depth', 'root']);
});

Schema::table('test_nodes_closure', function(Blueprint $table) {
    $table->foreign('ancestor_id')
        ->references('id')
        ->on('test_nodes')
        ->onDelete('cascade')
        ->onUpdate('cascade');
    $table->foreign('descendant_id')
        ->references('id')
        ->on('test_nodes')
        ->onDelete('cascade')
        ->onUpdate('cascade');
});
```

If I call `save()` on its own on a TestNode model it works ok, but if I call `save()` then `attachToSelf()` I get the error:

```php
stripos(): Argument #1 ($haystack) must be of type string, array given {"exception":"[object] (TypeError(code: 0): stripos(): Argument #1 ($haystack) must be of type string, array given at /classy/apiv2/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:62)"
```

**Comment by mikebridge** [comment]
I think this has something to do with `isRoot`:
```
"#0 /myapp/myapi/vendor/laravel/framework/src/Illuminate/Database/Grammar.php(62): stripos(Array, ' as ')",
"#1 [internal function]: Illuminate\\Database\\Grammar->wrap(Array)",
"#2 /myapp/myapi/vendor/laravel/framework/src/Illuminate/Database/Grammar.php(159): array_map(Array, Array)",
"#3 /myapp/myapi/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(718): Illuminate\\Database\\Grammar->columnize(Array)",
"#4 /myapp/myapi/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(101): Illuminate\\Database\\Query\\Grammars\\Grammar->compileGroups(Object(Illuminate\\Database\\Query\\Builder), Array)",
"#5 /myapp/myapi/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(75): Illuminate\\Database\\Query\\Grammars\\Grammar->compileComponents(Object(Illuminate\\Database\\Query\\Builder))",
"#6 /myapp/myapi/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(989): Illuminate\\Database\\Query\\Grammars\\Grammar->compileSelect(Object(Illuminate\\Database\\Query\\Builder))",
"#7 /myapp/myapi/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3030): Illuminate\\Database\\Query\\Grammars\\Grammar->compileExists(Object(Illuminate\\Database\\Query\\Builder))",
"#8 /myapp/myapi/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1869): Illuminate\\Database\\Query\\Builder->exists()",
"#9 /myapp/myapi/vendor/codrasil/closurable/src/Closurable.php(446): Illuminate\\Database\\Eloquent\\Builder->__call('exists', Array)",
"#10 /myapp/myapi/app/Jobs/Organization/TestNode/CreateTestNode.php(53): App\\Models\\TestNode\\TestNode->isRoot()",
```
